EquiforestWebApp/Models/Facturas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace EquiforestWebApp.Models
{
    public class Facturas
    {
        public int Id { get; set; }
        [Required,MaxLength(10)]
        [Display(Name = "Factura")]
        public string FacturaId { get; set; }
        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }
        [MaxLength(50)]
        public string Cliente { get; set; }
        [MaxLength(20)]
        public string Especie { get; set; }
        [MaxLength(20)]
        public string Finca { get; set; }
        [MaxLength(3)]
        public string Incoterm { get; set; }
        [MaxLength(20)]
        public string Destino { get; set; }
        [MaxLength(20)]
        [Display(Name = "Bill Of Lading")]
        public string BillOfLading { get; set; }
        public List<Contenedores> Contenedores { get; set; }
    }
}

EquiforestWebApp/Models/PackingList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EquiforestWebApp.Models
{
    public class PackingList
    {
        public int Id { get; set; }
        public DateTime Fecha { get; set; }
        [Required]
        public string Ubicacion { get; set; }
        public int Consecutivo { get; set; }
        public string Clase { get; set; }
        [Column(TypeName = "varchar(30)")]
        public string PackingListId { get; set; }
        public string Estado { get; set; }
        public float DescuentoCrc { get; set; }
        public float DescuentoLong { get; set; }
        [Column(TypeName = "varchar(20)")]
        public string ContenedorId { get; set; }
        public List<DetalleContenedores> DetalleContenedor { get; set; }
    }
}

EquiforestWebApp/Controllers/FacturasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EquiforestWebApp.Data;
using EquiforestWebApp.Models;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;
using System.IO;
using Microsoft.AspNetCore.JsonPatch;

namespace EquiforestWebApp.Controllers
{
    public class FacturasController : Controller
    {
        private readonly ApplicationDbContext _context;
 
        public FacturasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Facturas
        public async Task<IActionResult> Index(int? pageNumber, DateTime fecini, DateTime fecfin)
        {
            int pageSize = 10;
            var _fecini = fecini.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1) : fecini.Date;
            var _fecfin = fecfin.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)) : fecfin.Date;
            ViewData["FecIni"] = _fecini.ToString("yyyy-MM-dd");
            ViewData["FecFin"] = _fecfin.ToString("yyyy-MM-dd");

            //return View(await _context.Facturas.ToListAsync());
            return View(await PaginatedList<Facturas>.CreateAsync(_context.Facturas.Include(t => t.Contenedores).Where(f => f.Fecha >= _fecini && f.Fecha <= _fecfin).AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> PackingList(string Facturano, string packinglistid, DateTime fecini, DateTime fecfin, int origen)
        {
            var _fecini = fecini.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1) : fecini.Date;
            var _fecfin = fecfin.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)) : fecfin.Date;
            ViewData["FecIni"] = _fecini.ToString("yyyy-MM-dd");
            ViewData["FecFin"] = _fecfin.ToString("yyyy-MM-dd");

            List<Estratos> _estratos = new List<Estratos>();
            _estratos.Add(new Estratos { Id = 0, MinValue = 12, MaxValue = 13, Name = "12"});
            _estratos.Add(new Estratos { Id = 1, MinValue = 13, MaxValue = 14, Name = "13"});
            _estratos.Add(new Estratos { Id = 2, MinValue = 14, MaxValue = 15, Name = "14"});
            _estratos.Add(new Estratos { Id = 3, MinValue = 15, MaxValue = 16, Name = "15"});
            _estratos.Add(new Estratos { Id = 4, MinValue = 16, MaxValue = 17, Name = "16"});
            _estratos.Add(new Estratos { Id = 5, MinValue = 17, MaxValue = 18, Name = "17"});
            _estratos.Add(new Estratos { Id = 6, MinValue = 18, MaxValue = 19, Name = "18"});
            _estratos.Add(new Estratos { Id = 7, MinValue = 19, MaxValue = 20, Name = "19"});
            _estratos.Add(new Estratos { Id = 8, MinValue = 20, MaxValue = 21, Name = "20"});
            _estratos.Add(new Estratos { Id = 9, MinValue = 21, MaxValue = 22, Name = "21"});
            _estratos.Add(new Estratos { Id = 10, MinValue = 22, MaxValue = 23, Name = "22"});
            _estratos.Add(new Estratos { Id = 11, MinValue = 23, MaxValue = 24, Name = "23"});
            _estratos.Add(new Estratos { Id = 12, MinValue = 24, MaxValue = 25, Name = "24"});
            _estratos.Add(new Estratos { Id = 13, MinValue = 25, MaxValue = 99999, Name = "25",});

            List<Estratos> _estratoPrecios = new List<Estratos>();
            _estratoPrecios.Add(new Estratos { Id = 0, MinValue = 40, MaxValue = 45, Name = "40-44"});
            _estratoPrecios.Add(new Estratos { Id = 1, MinValue = 45, MaxValue = 50, Name = "45-49"});
            _estratoPrecios.Add(new Estratos { Id = 2, MinValue = 50, MaxValue = 55, Name = "50-54"});
            _estratoPrecios.Add(new Estratos { Id = 3, MinValue = 55, MaxValue = 60, Name = "55-59"});
            _estratoPrecios.Add(new Estratos { Id = 4, MinValue = 60, MaxValue = 65, Name = "60-64"});
            _estratoPrecios.Add(new Estratos { Id = 5, MinValue = 65, MaxValue = 70, Name = "65-69"});
            _estratoPrecios.Add(new Estratos { Id = 6, MinValue = 70, MaxValue = 75, Name = "70-74"});
            _estratoPrecios.Add(new Estratos { Id = 7, MinValue = 75, MaxValue = 80, Name = "75-79"});
            _estratoPrecios.Add(new Estratos { Id = 8, MinValue = 80, MaxValue = 85, Name = "80-84"});
            _estratoPrecios.Add(new Estratos { Id = 9, MinValue = 85, MaxValue = 90, Name = "85-89"});
            _estratoPrecios.Add(new Estratos { Id = 10, MinValue = 90, MaxValue = 99999, Name = "90->>"});

            ViewData["Estratos"] = _estratos;
            ViewData["EstratosPrecios"] = _estratoPrecios;
            ViewData["ShowFilter"] = true;
            ViewData["Precios"] = null;
            List<PackingListResumen> model = null;

            switch (origen)
            {
                //Comes from Factura
                case 1:
                    ViewData["ShowFilter"] = false;
                    var result1 = 
                        from s in _context.DetalleContenedores
                                 join v in _context.PackingList on s.PackingListId equals v.PackingListId
                                 join c in _context.Contenedores on v.PackingListId equals c.PackingListId
                                 join f in _context.Facturas on c.FacturaId equals f.FacturaId
                                 where f.FacturaId == Facturano
                                 select new PackingListResumen
                                 {
                                     Cliente = f.Cliente,
                                     Fecha = f.Fecha,
                                     FacturaId = f.FacturaId,
                                     Cabezal = c.Cabezal,
                                     Especie = f.Especie,
                                     Calidad = v.Clase,
                                     ContenedorId = c.ContenedorId,
                                     Finca = f.Finca,
                                     Chofer = c.Chofer,
                                     Sello = c.Sello,
                                     Grupo = "Trozas con corteza",
                                     PackingListId = v.PackingListId,
                                     Diametro = Convert.ToSingle(s.Circunferencia / Math.PI),
                                     Largo = s.Longitud,
                                     Volumen = MathF.Round((float)(((s.Circunferencia * s.Circunferencia) / (4 * Math.PI)) * s.Longitud / 10000), 2),
                                     VolumenH = Convert.ToSingle((Math.Pow(((s.Circunferencia / 100.0f) - v.DescuentoCrc), 2) * (s.Longitud - v.DescuentoLong) / 16)),
                                 };
                    
                    model = await result1.OrderBy(o => o.Fecha).ThenBy(o => o.FacturaId).AsNoTracking().ToListAsync();
                    break;
                
                //Comes from PackingList - Global
                case 2:
                    var result2 = from s in _context.DetalleContenedores
                                 join v in _context.PackingList on s.PackingListId equals v.PackingListId
                                 where v.Fecha >= _fecini && v.Fecha <= _fecfin && v.ContenedorId == null
                                 select new PackingListResumen
                                 {
                                     Cliente = "",
                                     Fecha = v.Fecha,
                                     FacturaId = "",
                                     Cabezal = "",
                                     Especie = "Teca",
                                     Calidad = v.Clase,
                                     ContenedorId = "",
                                     Finca = v.Ubicacion,
                                     Chofer = "",
                                     Sello = "",
                                     Grupo = "Trozas con corteza",
                                     PackingListId = v.PackingListId,
                                     Diametro = Convert.ToSingle(s.Circunferencia / Math.PI),
                                     Largo = s.Longitud,
                                     Volumen = MathF.Round((float)(((s.Circunferencia * s.Circunferencia) / (4 * Math.PI)) * s.Longitud / 10000), 2)
                                 };
                    model = await result2.OrderBy(o => o.Fecha).ThenBy(o => o.FacturaId).AsNoTracking().ToListAsync();
                    break;
                
                //Comes from PackingList - Print
                case 3:
                    ViewData["ShowFilter"] = false;
                    var result3 = from s in _context.DetalleContenedores
                                  join v in _context.PackingList on s.PackingListId equals v.PackingListId
                                  where v.PackingListId == packinglistid
                                  select new PackingListResumen
                                  {
                                      Cliente = "",
                                      Fecha = v.Fecha,
                                      FacturaId = "",
                                      Cabezal = "",
                                      Especie = "Teca",
                                      Calidad = v.Clase,
                                      ContenedorId = "",
                                      Finca = v.Ubicacion,
                                      Chofer = "",
                                      Sello = "",
                                      Grupo = "Trozas con corteza",
                                      PackingListId = v.PackingListId,
                                      Diametro = Convert.ToSingle(s.Circunferencia / Math.PI),
                                      Largo = s.Longitud,

EquiforestWebApp/Views/Facturas/Create.cshtml
@model EquiforestWebApp.Models.Facturas

@{
    ViewData["Title"] = "Create";
}

<h2>Crear</h2>

<h4>Facturas</h4>
<hr />
<div class="row">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-md-4 col-xs-6">
            <div class="form-group">
                <label asp-for="FacturaId" class="control-label"></label>
                <input asp-for="FacturaId" class="form-control" />
                <span asp-validation-for="FacturaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Finca" class="control-label"></label>
                <select asp-for="Finca" class="form-control" asp-items="ViewBag.Fincas">
                    <option selected="selected" value="">Seleccionar la finca</option>
                </select>
                @*<input asp-for="Finca" class="form-control" />*@
                <span asp-validation-for="Finca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Especie" class="control-label"></label>
                <input asp-for="Especie" class="form-control" />
                <span asp-validation-for="Especie" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4 col-xs-6">
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                <input asp-for="Cliente" class="form-control" />
                <span asp-validation-for="Cliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destino" class="control-label"></label>
                <input asp-for="Destino" class="form-control" />
                <span asp-validation-for="Destino" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillOfLading" class="control-label"></label>
                <input asp-for="BillOfLading" class="form-control" />
                <span asp-validation-for="BillOfLading" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Incoterm" class="control-label"></label>
                @*<input asp-for="Incoterm" class="form-control" />*@
                <select asp-for="Incoterm" class="form-control" asp-items="ViewBag.Incoterms">
                    <option selected="selected" value="@ViewBag.IncotermSelected">@ViewBag.IncotermSelected</option>
                </select>
                <span asp-validation-for="Incoterm" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4 col-xs-6">
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </form>
</div>

<div>
    <a asp-action="Index"><span class="glyphicon glyphicon-arrow-left"></span></a>
</div>

EquiforestWebApp/Views/Facturas/Delete.cshtml
@model EquiforestWebApp.Models.Facturas

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Facturas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FacturaId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FacturaId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cliente)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Especie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Especie)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Finca)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Finca)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Incoterm)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Incoterm)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Destino)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Destino)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillOfLading)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillOfLading)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EquiforestWebApp/Views/Facturas/Details.cshtml
@model EquiforestWebApp.Models.Facturas

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Facturas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FacturaId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FacturaId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cliente)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Especie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Especie)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Finca)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Finca)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Incoterm)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Incoterm)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Destino)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Destino)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillOfLading)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillOfLading)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EquiforestWebApp/Views/Facturas/Edit.cshtml
@model EquiforestWebApp.Models.Facturas

@{
    ViewData["Title"] = "Edit";
}

<h2>Editar</h2>

<h5>Facturas</h5>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" name="fecini" value="@ViewBag.FecIni" />
            <input type="hidden" name="fecfin" value="@ViewBag.FecFin" />
            <div class="form-group">
                <label asp-for="FacturaId" class="control-label"></label>
                <input asp-for="FacturaId" class="form-control" />
                <span asp-validation-for="FacturaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cliente" class="control-label"></label>
                <input asp-for="Cliente" class="form-control" />
                <span asp-validation-for="Cliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Especie" class="control-label"></label>
                <input asp-for="Especie" class="form-control" />
                <span asp-validation-for="Especie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Finca" class="control-label"></label>
                @*<input asp-for="Finca" class="form-control" />*@
                <select asp-for="Finca" class="form-control" asp-items="ViewBag.Fincas">
                    <option selected="selected" value="@ViewBag.FincaSelected">@ViewBag.FincaSelected</option>
                </select>

                <span asp-validation-for="Finca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Incoterm" class="control-label"></label>
                @*<input asp-for="Incoterm" class="form-control" />*@
                <select asp-for="Incoterm" class="form-control" asp-items="ViewBag.Incoterms">
                    <option selected="selected" value="@ViewBag.IncotermSelected">@ViewBag.IncotermSelected</option>
                </select>
                <span asp-validation-for="Incoterm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destino" class="control-label"></label>
                <input asp-for="Destino" class="form-control" />
                <span asp-validation-for="Destino" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillOfLading" class="control-label"></label>
                <input asp-for="BillOfLading" class="form-control" />
                <span asp-validation-for="BillOfLading" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-fecini="@ViewBag.FecIni" asp-route-fecfin="@ViewBag.FecFin">Regresar</a>
</div>

EquiforestWebApp/Views/Facturas/PackingList.cshtml
@model List<PackingListResumen>
@{
    ViewData["Title"] = "Packing List";
}

<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0px";
    }
</script>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a asp-controller="Facturas" asp-action="Index">Facturas</a>
    <a asp-controller="Contenedores" asp-action="Index">Contenedores</a>
    <a asp-controller="Facturas" asp-action="PackingList" asp-route-origen="2">Packing List</a>
</div>

<h4><span style="font-size:20px;cursor:pointer" onclick="openNav()">&#9776; Comercializacion</span></h4>

@if (ViewBag.ShowFilter)
{
    <h2>Packing List - Standby</h2>
}
else
{
    <h2>Packing List - Factura @ViewBag.Factura</h2> <a asp-controller="Facturas" asp-action="Index" asp-route-fecini="@ViewBag.FecIni" asp-route-fecfin="@ViewBag.FecFin">Regresar</a>
}

@if (ViewBag.ShowFilter)
{
    <div class="row">
        <div class="col-md-6 col-xs-4">
            <form asp-controller="Facturas" asp-action="PackingList" asp-route-origen="2">
                <div class="form form-inline">
                    <p>
                        <input type="hidden" name="pageNumber" value="1" />
                        <input type="date" class="form-control" name="fecini" value="@ViewData["FecIni"]" />
                        <input type="date" class="form-control" name="fecfin" value="@ViewData["FecFin"]" />
                        <input type="submit" asp- value="Filtrar" class="btn btn-default" />
                    </p>
                </div>
            </form>
        </div>
    </div>
}


<div class="row">

    @foreach (var cont in ViewBag.PackingList)
    {
        <div class="col-md-4">
            <div class="table-bordered myMargen">
                <table class="table bg-primary">
                    <caption class="text-center"><a asp-controller="Facturas" asp-action="PackingList" asp-route-packinglistid="@cont.Key" asp-route-origen="3">@cont.Key</a></caption>
                    <thead>
                        <tr>
                            <th style="width:50%">
                                <h5>Cliente : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.Cliente)</h5>
                            </th>
                            <th>
                                <h5>Fecha   : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.Fecha).ToShortDateString()</h5>
                            </th>
                        </tr>

                        <tr>
                            <th>
                                <h5>Factura : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.FacturaId)</h5>
                            </th>
                            <th>
                                <h5>Cabezal : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.Cabezal)</h5>
                            </th>
                        </tr>

                        <tr>
                            <th>
                                <h5>Calidad : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.Calidad)</h5>
                            </th>
                            <th>
                                <h5>Contenedor : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.ContenedorId)</h5>
                            </th>
                        </tr>

                        <tr>
                            <th>
                                <h5>Finca : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.Finca)</h5>
                            </th>
                            <th>
                                <h5>Chofer : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.Chofer)</h5>
                            </th>
                        </tr>

                        <tr>
                            <th>
                                <h5>Sello : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.Sello)</h5>
                            </th>
                            <th>
                                <h5>Grupo Producto : @Model.Where(w => w.PackingListId == cont.Key).Max(c => c.Grupo)</h5>
                            </th>
                        </tr>
                    </thead>
                </table>

                <table class="table">
                    <thead>
                        <tr>
                            <th>Cantidad</th>
                            <th>Especie</th>
                            <th>Diametro</th>
                            <th>Largo</th>
                            <th>Volumen</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in ViewBag.Estratos)
                        {
                            <tr>
                                <td>@string.Format("{0:#,0.00}", Model.Where(f => f.Diametro >= item.MinValue && f.Diametro < item.MaxValue && f.PackingListId == cont.Key).Count())</td>
                                <td>@Model.Where(f => f.PackingListId == cont.Key).Max(e => e.Especie)</td>
                                <td>@item.Name</td>
                                <td>@Model.Where(f => f.PackingListId == cont.Key).Max(e => e.Largo)</td>
                                <td>@string.Format("{0:#,0.00}", Model.Where(f => f.Diametro >= item.MinValue && f.Diametro < item.MaxValue && f.PackingListId == cont.Key).Sum(s => s.Volumen))</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>

    }
</div>

@if (ViewBag.Precios != null)
{
    <div class="row">
        <div class="col-md-12">
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Rango</th>
                        <th>Volumen A </th>
                        <th>Precio A</th>
                        <th>Cantidad A</th>
                        <th>Costo USD A</th>
                        <th>Volumen B </th>
                        <th>Precio B</th>
                        <th>Cantidad B</th>
                        <th>Costo USD B</th>
                        <th>Volumen C </th>
                        <th>Precio C</th>
                        <th>Cantidad C</th>
                        <th>Costo USD C</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in ViewBag.Precios)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.VolumenA</td>
                            <td>@item.PrecioA</td>
                            <td>@item.CantidadA</td>
                            <td><strong>@item.CostoA</strong></td>
                            <td>@item.VolumenB</td>
                            <td>@item.PrecioB</td>
                            <td>@item.CantidadB</td>
                            <td><strong>@item.CostoB</strong></td>
                            <td>@item.VolumenC</td>
                            <td>@item.PrecioC</td>
                            <td>@item.CantidadC</td>
                            <td><strong>@item.CostoC</strong></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}