EquiforestWebApp/Models/Trozas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EquiforestWebApp.Models
{
    public class Trozas
    {
        public int Id { get; set; }
        [Required]
        public string Clasificacion { get; set; }
        [Required]
        public float? Circunferencia { get; set; }
        [Required]
        public float? Largo { get; set; }
        [Column(TypeName = "varchar(30)")]
        public string ViajeId { get; set; }
        [ForeignKey("ViajeId")]
        public Viajes Viaje { get; set; }
    }
}

EquiforestWebApp/Controllers/TrozasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EquiforestWebApp.Data;
using EquiforestWebApp.Models;

namespace EquiforestWebApp.Controllers
{
    public class TrozasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TrozasController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGetTrozasEdit(int id)
        {
            //GetSelectedListItem();
            var model = _context.Trozas.SingleOrDefault(m => m.Id == id);
            return PartialView("/Views/Trozas/_TrozasEdit.cshtml", model);
        }

        // GET: Trozas
        public async Task<IActionResult> Index(int? pageNumber, string id)
        {

            ViewData["viajeId"] = id;

            int pageSize = 10;
            //return View(await _context.Trozas.ToListAsync());
            return View(await PaginatedList<Trozas>.CreateAsync(_context.Trozas.Where(f => f.ViajeId == id).AsNoTracking().AsQueryable(), pageNumber ?? 1, pageSize));
        }

        //public async Task<IActionResult> Trozas(int? pageNumber, DateTime fecini, DateTime fecfin)
        //{

        //}

        public async Task<IActionResult> Resumen()
        {
            //var result = from s in _context.Trozas join v in _context.Viajes on s.ViajesId equals v.Id
            //             select new ResumenCosecha { Circunferencia = s.Circunferencia, Clasificacion = s.Clasificacion, Largo = s.Largo, Volumen = ((Math.Sqrt((Double)s.Circunferencia))/(4*Math.PI))*s.Largo/10000 };
            // return View(await result.AsNoTracking().ToListAsync());
            return View(await _context.Trozas.AsNoTracking().ToListAsync());
        }

        // GET: Trozas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trozas = await _context.Trozas
                .SingleOrDefaultAsync(m => m.Id == id);
            if (trozas == null)
            {
                return NotFound();
            }

            return View(trozas);
        }

        // GET: Trozas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trozas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Clasificacion,Circunferencia,Largo")] Trozas trozas, string id)
        {
            if (ModelState.IsValid)
            {
                trozas.ViajeId = id;
                trozas.ViajeId = id;
                _context.Add(trozas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = id });
            }

            return View(trozas);
        }

        public async Task<IActionResult> EditModal(int id, Trozas trozas)
        {
            if (id != trozas.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trozas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                }
                return RedirectToAction(nameof(Index));
            }
            return View(trozas);
        }

        private bool TrozasExists(string id)
        {
            return _context.Trozas.Any(e => e.ViajeId == id);
        }

        // GET: Trozas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trozas = await _context.Trozas.SingleOrDefaultAsync(m => m.Id == id);
            if (trozas == null)
            {
                return NotFound();
            }
            return View(trozas);
        }

        // POST: Trozas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdViaje,Clasificacion,Circunferencia,Largo")] Trozas trozas)
        {
            if (id != trozas.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trozas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrozasExists(trozas.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = trozas.ViajeId } );
            }
            return View(trozas);
        }

        // GET: Trozas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var troza = await _context.Trozas
                .SingleOrDefaultAsync(m => m.Id == id);

            if (troza == null)
            {
                return NotFound();
            }

            _context.Trozas.Remove(troza);
            await _context.SaveChangesAsync();

            //return View(troza);
            return RedirectToAction(nameof(Index), new { id = troza.ViajeId });
        }

        // GET: Trozas/Delete/123asd
                public async Task<IActionResult> DeletebyViajeId (string viajeId)
                {
                    if (viajeId == null)
                    {
                        return NotFound();
                    }

                    var trozas = _context.Trozas.Where(m => m.ViajeId == viajeId);

                    if (trozas == null)
                    {
                        return NotFound();
                    }

                    _context.Trozas.RemoveRange(trozas);
                    await _context.SaveChangesAsync();

                    return Ok(trozas);
                } 

                // POST: Trozas/Delete/5
                [HttpPost, ActionName("Delete")]
                [ValidateAntiForgeryToken]
                public async Task<IActionResult> DeleteConfirmed(int id)
                {
                    var trozas = await _context.Trozas.SingleOrDefaultAsync(m => m.Id == id);
                    _context.Trozas.Remove(trozas);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

                private bool TrozasExists(int id)
                {
                    return _context.Trozas.Any(e => e.Id == id);
                }
            }
        }

EquiforestWebApp/Views/Trozas/Create.cshtml
@model EquiforestWebApp.Models.Trozas

@{
    ViewData["Title"] = "Registrar Trozas";
}

<h2>Crear Trozas</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Clasificacion" class="control-label"></label>
                <input asp-for="Clasificacion" class="form-control" />
                <span asp-validation-for="Clasificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Circunferencia" class="control-label"></label>
                <input asp-for="Circunferencia" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Circunferencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Largo" class="control-label"></label>
                <input asp-for="Largo" class="form-control" />
                <span asp-validation-for="Largo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EquiforestWebApp/Views/Trozas/Delete.cshtml
@model EquiforestWebApp.Models.Trozas

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trozas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Clasificacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Clasificacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Circunferencia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Circunferencia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Largo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Largo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EquiforestWebApp/Views/Trozas/Details.cshtml
@model EquiforestWebApp.Models.Trozas

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Trozas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Clasificacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Clasificacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Circunferencia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Circunferencia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Largo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Largo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-route-id="@Model.ViajeId" asp-action="Index">Back to List</a>
</div>

EquiforestWebApp/Views/Trozas/Edit.cshtml
@model EquiforestWebApp.Models.Trozas

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Trozas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Clasificacion" class="control-label"></label>
                <input asp-for="Clasificacion" class="form-control" />
                <span asp-validation-for="Clasificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Circunferencia" class="control-label"></label>
                <input asp-for="Circunferencia" class="form-control" />
                <span asp-validation-for="Circunferencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Largo" class="control-label"></label>
                <input asp-for="Largo" class="form-control" />
                <span asp-validation-for="Largo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Viajes" asp-action="Viaje">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EquiforestWebApp/Views/Trozas/Index.cshtml
@*@model IEnumerable<EquiforestWebApp.Models.Trozas>*@
@model PaginatedList<EquiforestWebApp.Models.Trozas>

@{
    ViewData["Title"] = "Index";
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script>

    function showModal(Id) {

            $.ajax({
                url: '/Trozas/OnGetTrozasEdit',
                type: 'GET',
                data: { id: Id },
                error: function (data) {
                    alert("Error at getting" + data);
                },
                success: function (data) {
                    $('#div_content').html(data);
                    $('#TrozaModal').modal('show');
                }
            });

    }

    $(document).on('click', '#saveModal', function () {

        $.ajax({

            url: '@Url.Action("EditModal", "Trozas")',
            type: "PUT",
            data: {

                id: $("#Id").val(),
                clasificacion: $("#Clasificacion").val(),
                circunferencia: $("#Circunferencia").val(),
                largo: $("#Largo").val(),
                viaje: $("#Viaje").val(),
                viajeId: $("#ViajeId").val()
            },

            error: function () {
                alert("Error al actualizar trozas");
            },

            success: function () {
                $("#ViajeModal").modal('hide');
                location.reload();

            },

        });

    });

</script>

<div>

    <div style=" display:inline-block; width: 9%;">
        <h2>Trozas</h2>
    </div>

    <p style=" display:inline-block";>
        <a asp-route-id="@ViewBag.viajeId" asp-action="Create" class="btn btn-info">Crear Troza </a>
    </p>

</div>

<input type="hidden" class="form-control" name="viajeId" value="@ViewData["viajeId"]" />

<div>
    <!-- Modal -->
    <div class="modal fade" id="TrozaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Editar Troza</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="div_content">
                    <!--<partial name="_ViajesEdit.cshtml" />-->
                </div>
            </div>
        </div>
    </div>
</div>

@* <div>
        <form asp-action="Index" method="get">
            <div class="form-actions no-color">
                <p>
                    <input type="date" class="input-group" name="fecini" value="@ViewData["FecIni"]"/>
                    <input type="date" class="input-group" name="fecfin" value="@ViewData["FecFin"]"/>
                    <input type="submit" value="Filtrar" class="btn btn-default" />
                </p>
            </div>
        </form>
    </div>

*@



<table class="table">
    <thead>
        <tr>
            @*
                <th>Nucleo</th>
                <th>Finca</th>
                <th>Rodal</th>
                <th>Fecha</th>
                <th>Ubicacion</th>
                <th>N_Viaje</th>
            *@
            <th>Clasificacion</th>
            <th>Circunferencia</th>
            <th>Largo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*
                    <td>
                        @Html.DisplayFor(modelItem => item.Viaje.Nucleo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Viaje.Finca)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Viaje.Rodal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Viaje.FechaIngreso)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Viaje.Ubicacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Viaje.N_Viaje)
                    </td>
                *@

                <td>
                    @Html.DisplayFor(modelItem => item.Clasificacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Circunferencia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Largo)
                </td>
                <td>

                    @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> *@
                    <a id="btn-trigger-modal" class="btn btn-default" onclick="showModal(@item.Id)" style="cursor:pointer" ;>Edit</a>
                    @*                     <a asp-action="Details" asp-route-id="@item.Id">Details</a> *@
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>

<div>
    <a asp-controller="Viajes" asp-action="Viaje">Back to List</a>
</div>

EquiforestWebApp/Views/Trozas/_TrozasEdit.cshtml
@model EquiforestWebApp.Models.Trozas

<form asp-action="TrozasEdit">
    <input type="hidden" asp-for="Id" id="Id" class="form-control" />
    <div class="form-group">
        <label for="Clasificacion" class="control-label">Clasificacion</label>
        <input asp-for="Clasificacion" class="form-control" name="Clasificacion" id="Clasificacion" />
        <span asp-validation-for="Clasificacion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Circunferencia" class="control-label">Circunferencia</label>
        <input asp-for="Circunferencia" class="form-control" name="Circunferencia" id="Circunferencia" />
        <span asp-validation-for="Circunferencia" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Largo" class="control-label">Largo</label>
        <input asp-for="Largo" class="form-control" name="Largo" id="Largo" />
        <span asp-validation-for="Largo" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="Viaje" id="Viaje" class="form-control" />
    <input type="hidden" asp-for="ViajeId" id="ViajeId" class="form-control" />
</form>
<div class="modal-footer">
    <button type="button" class="btn btn-primary" id="saveModal">Save</button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>