EquiforestWebApp/Models/Viajes.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EquiforestWebApp.Models
{
    public class Viajes
    {
        public int Id { get; set; }
        [Column(TypeName = "varchar(30)")]
        public string ViajeId { get; set; }
        [Required]
        public string Nucleo { get; set; }
        [Required]
        public string Finca { get; set; }
        [Required]
        public string Rodal { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Ingreso")]
        public DateTime FechaIngreso { get; set; }
        [Required]
        public string Ubicacion { get; set; }
        [Required]
        public int? N_Viaje { get; set; }
        [Display(Name = "Trozas C")]
        public int? NoTrozasC { get; set; }
        public List<Trozas> Trozas { get; set; }
        [NotMapped]
        public List<SelectListItem> Nucleos { get; set; }
        [NotMapped]
        public List<SelectListItem> Fincas { get; set; }
        [NotMapped]
        public List<SelectListItem> Rodales { get; set; }
    }
}

EquiforestWebApp/Controllers/ViajesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EquiforestWebApp.Data;
using EquiforestWebApp.Models;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;
using System.IO;

namespace EquiforestWebApp.Controllers
{
    public class ViajesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly TrozasController _trozasController;

        public ViajesController(ApplicationDbContext context)
        {
            _context = context;
            _trozasController = new TrozasController(context);
        }

        // GET: Viajes
        public IActionResult Index(int? pageNumber, DateTime fecini, DateTime fecfin, bool download, string rodal, string finca)
        {
            int pageSize = 15;
            var _fecini = fecini.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1) : fecini.Date;
            var _fecfin = fecfin.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)) : fecfin.Date;
            ViewData["FecIni"] = _fecini.ToString("yyyy-MM-dd");
            ViewData["FecFin"] = _fecfin.ToString("yyyy-MM-dd");

            List<ViajesGroup> viajesgroupList = new List<ViajesGroup>();
            if (finca == null && rodal == null)
            {
                var result = from s in _context.Viajes
                             join t in _context.Trozas
                             on s.ViajeId equals t.ViajeId into joinViajes
                             where s.FechaIngreso >= _fecini && s.FechaIngreso <= _fecfin
                             from tr in joinViajes.DefaultIfEmpty()
                             select new
                             {
                                 Nucleo = s.Nucleo,
                                 Finca = s.Finca,
                                 Rodal = s.Rodal,
                                 Fecha = s.FechaIngreso,
                                 Ubicacion = s.Ubicacion,
                                 N_Viaje = (int)s.N_Viaje,
                                 NoTrozasC = s.NoTrozasC,
                                 Clasificacion = tr == null ? "" : tr.Clasificacion,
                                 Circunferencia = tr == null ? 0f : tr.Circunferencia,
                                 Longitud = tr == null ? 0f : tr.Largo,
                                 Volumen = tr == null ? 0f : MathF.Round((float)(((tr.Circunferencia * tr.Circunferencia) / (4 * Math.PI)) * tr.Largo / 10000), 2)
                             };
                var viajesgroupresult = result.OrderBy(o => o.Fecha).ThenBy(o => o.N_Viaje).ThenBy(o => o.Clasificacion).GroupBy(g => new { g.Nucleo, g.Finca, g.Rodal, g.Fecha, g.Ubicacion, g.N_Viaje, g.Clasificacion });
                foreach (var viaje in viajesgroupresult)
                {
                    viajesgroupList.Add(new ViajesGroup
                    {
                        Nucleo = viaje.Key.Nucleo,
                        Finca = viaje.Key.Finca,
                        Rodal = viaje.Key.Rodal,
                        Fecha = viaje.Key.Fecha,
                        Ubicacion = viaje.Key.Ubicacion,
                        N_Viaje = viaje.Key.N_Viaje,
                        Clasificacion = viaje.Key.Clasificacion,
                        Circunferencia = viaje.Average(c => c.Circunferencia),
                        Longitud = viaje.Average(l => l.Longitud),
                        Cantidad = viaje.Sum(v => v.Volumen) > 0 ? viaje.Count() : 0,
                        Volumen = viaje.Sum(v => v.Volumen),
                        NoTrozasC = viaje.Max(t => t.NoTrozasC)
                    });
                }
            }
            else if (finca != null && rodal == null)
            {
                var result = from s in _context.Viajes
                             join t in _context.Trozas
                             on s.ViajeId equals t.ViajeId into joinViajes
                             where s.FechaIngreso >= _fecini && s.FechaIngreso <= _fecfin && s.Finca == finca
                             from tr in joinViajes.DefaultIfEmpty()
                             select new
                             {
                                 Nucleo = s.Nucleo,
                                 Finca = s.Finca,
                                 Rodal = s.Rodal,
                                 Fecha = s.FechaIngreso,
                                 Ubicacion = s.Ubicacion,
                                 N_Viaje = (int)s.N_Viaje,
                                 NoTrozasC = s.NoTrozasC,
                                 Clasificacion = tr == null ? "" : tr.Clasificacion,
                                 Circunferencia = tr == null ? 0f : tr.Circunferencia,
                                 Longitud = tr == null ? 0f : tr.Largo,
                                 Volumen = tr == null ? 0f : MathF.Round((float)(((tr.Circunferencia * tr.Circunferencia) / (4 * Math.PI)) * tr.Largo / 10000), 2)
                             };
                var viajesgroupresult = result.OrderBy(o => o.Fecha).ThenBy(o => o.N_Viaje).ThenBy(o => o.Clasificacion).GroupBy(g => new { g.Nucleo, g.Finca, g.Rodal, g.Fecha, g.Ubicacion, g.N_Viaje, g.Clasificacion });
                foreach (var viaje in viajesgroupresult)
                {
                    viajesgroupList.Add(new ViajesGroup
                    {
                        Nucleo = viaje.Key.Nucleo,
                        Finca = viaje.Key.Finca,
                        Rodal = viaje.Key.Rodal,
                        Fecha = viaje.Key.Fecha,
                        Ubicacion = viaje.Key.Ubicacion,
                        N_Viaje = viaje.Key.N_Viaje,
                        Clasificacion = viaje.Key.Clasificacion,
                        Circunferencia = viaje.Average(c => c.Circunferencia),
                        Longitud = viaje.Average(l => l.Longitud),
                        Cantidad = viaje.Sum(v => v.Volumen) > 0 ? viaje.Count() : 0,
                        Volumen = viaje.Sum(v => v.Volumen),
                        NoTrozasC = viaje.Max(t => t.NoTrozasC)
                    });
                }
            }
            else if (rodal != null)
            {
                var result = from s in _context.Viajes
                             join t in _context.Trozas
                             on s.ViajeId equals t.ViajeId into joinViajes
                             where s.FechaIngreso >= _fecini && s.FechaIngreso <= _fecfin && s.Rodal == rodal
                             from tr in joinViajes.DefaultIfEmpty()
                             select new
                             {
                                 Nucleo = s.Nucleo,
                                 Finca = s.Finca,
                                 Rodal = s.Rodal,
                                 Fecha = s.FechaIngreso,
                                 Ubicacion = s.Ubicacion,
                                 N_Viaje = (int)s.N_Viaje,
                                 NoTrozasC = s.NoTrozasC,
                                 Clasificacion = tr == null ? "" : tr.Clasificacion,
                                 Circunferencia = tr == null ? 0f : tr.Circunferencia,
                                 Longitud = tr == null ? 0f : tr.Largo,
                                 Volumen = tr == null ? 0f : MathF.Round((float)(((tr.Circunferencia * tr.Circunferencia) / (4 * Math.PI)) * tr.Largo / 10000), 2)
                             };
                var viajesgroupresult = result.OrderBy(o => o.Fecha).ThenBy(o => o.N_Viaje).ThenBy(o => o.Clasificacion).GroupBy(g => new { g.Nucleo, g.Finca, g.Rodal, g.Fecha, g.Ubicacion, g.N_Viaje, g.Clasificacion });
                foreach (var viaje in viajesgroupresult)
                {
                    viajesgroupList.Add(new ViajesGroup
                    {
                        Nucleo = viaje.Key.Nucleo,
                        Finca = viaje.Key.Finca,
                        Rodal = viaje.Key.Rodal,
                        Fecha = viaje.Key.Fecha,
                        Ubicacion = viaje.Key.Ubicacion,
                        N_Viaje = viaje.Key.N_Viaje,
                        Clasificacion = viaje.Key.Clasificacion,
                        Circunferencia = viaje.Average(c => c.Circunferencia),
                        Longitud = viaje.Average(l => l.Longitud),
                        Cantidad = viaje.Sum(v => v.Volumen) > 0 ? viaje.Count() : 0,
                        Volumen = viaje.Sum(v => v.Volumen),
                        NoTrozasC = viaje.Max(t => t.NoTrozasC)
                    });
                }
            }

            //return View(await _context.Trozas.ToListAsync());
            if (download)
            {
                Download(viajesgroupList, "Viajes.xlsx");
            }
            var fincas = GetFincas();
            ViewData["Fincas"] = fincas;
            ViewData["FincaSelected"] = finca;
            var rodales = GetRodales();
            ViewData["Rodales"] = rodales;
            var _finca = "";
            if (rodal != null)
            {
                _finca = rodales.Find(m => m.Value == rodal).Text;
            }
            ViewData["RodalSelected"] = rodal;
            ViewData["RodalSelectedText"] = _finca;

            return View(PaginatedList<ViajesGroup>.Create(viajesgroupList.AsQueryable(), pageNumber ?? 1, pageSize));
            //return View(await PaginatedList<Trozas>.CreateAsync(_context.Trozas.Include(t => t.Viaje).Where(f => f.Viaje.FechaIngreso >= _fecini && f.Viaje.FechaIngreso <= _fecfin).AsNoTracking(), pageNumber ?? 1, pageSize));

            //return View(await _context.Viajes.ToListAsync());
        }

EquiforestWebApp/Views/Viajes/Index.cshtml
@model PaginatedList<EquiforestWebApp.Models.ViajesGroup>

@{
    ViewData["Title"] = "Detalle de cosecha";
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}


<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    // Handle "Edit Person" button click.
    // This will make an ajax call, get information for person,
    // put it all in the modal and display it
    $(document).on('click', '#btn-trigger-modal', function () {
        var viajeId = $(this).data('id');
        $.ajax({
            url: '/Viajes/OnGetViajesCreate',
            type: 'GET',
            data: { id: viajeId },
            success: function (data) {
                $('#div_content').html(data);
//                $('#nucleo').text(data.nucleo);
                $('#exampleModal').modal('show');
            }
        });
    });

    // Handle submitting of new information for Person.
    // This will attempt to save new info
    // If save was successful, it will close the Modal and reload page to see updated info
    // Otherwise it will only reload contents of the Modal
    $(document).on('click', '#saveModal', function () {
        var self = $(this);
        var actionUrl = '/Viajes/OnPostViajesCreate';
        var dataToSend = self.parents('.modal').find('form').serialize();

        $.post(actionUrl, dataToSend).done(function (data) {
            //console.log(data);
            $('#div_content').html(data);
            var newBody = $('.modal-body', data);
            var valValid = $('#div_content').find('[name="IsValid"]').val();
            var isValid = valValid == 'True';
                //newBody.find('[name="IsValid"]').val() == 'True';

            if (isValid) {
                $('#exampleModal').modal('hide');
                location.reload(false);
            }
        });


        @*$.ajax({
            url: '/Viajes/EditModal/' + $('#Id').val(),
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            data: self.parents('.modal').find('form').serialize(),
            success: function (data) {
                if (data.success == true) {
                    $('#modal-person').modal('hide');
                    location.reload(false)
                } else {
                    $('#modal-person').html(data);
                }
            }
        });*@
    });
</script>


<h3>Detalle de Cosecha</h3>
<div class="row">
    
        <form asp-controller="Viajes" asp-action="Index" method="get">
            <div class="form">

                <input type="hidden" name="pageNumber" value="1" />
                <div class="col-md-2">
                    <label for="fecini">Desde</label>
                    <input type="date" class="form-control" name="fecini" value="@ViewData["FecIni"]" />
                </div>
                <div class="col-md-2">
                    <label for="fecfin">Hasta</label>
                    <input type="date" class="form-control" name="fecfin" value="@ViewData["FecFin"]" />
                </div>
                <div class="col-md-3">
                    <label for="finca">Finca</label>
                    <select asp-items="ViewBag.Fincas" name="Finca" class="form-control">
                        <option selected="selected" value="@ViewBag.FincaSelected">@ViewBag.FincaSelected</option>
                    </select>
                </div>
                <div class="col-md-2">
                    <label for="rodal">Rodal</label>
                    <select asp-items="ViewBag.Rodales" name="Rodal" class="form-control">
                        <option selected="selected" value="@ViewBag.RodalSelected">@ViewBag.RodalSelectedText</option>
                    </select>
                    <input type="submit" value="Filtrar" class="btn btn-default" />
                </div>
            </div>
</form>
  
</div>

    <p>
        <a href="#" id="btn-trigger-modal" class="btn btn-info">Create New</a>
    </p>

<table class="table table-responsive">
    <thead>
        <tr>
            <th>
                Nucleo
            </th>
            <th>
                Finca
            </th>
            <th>
                Rodal
            </th>
            <th>
                Fecha
            </th>
            <th>
                Ubicacion
            </th>
            <th>
                N_Viaje
            </th>
            <th>
                No. Trozas "C"
            </th>
            <th>
                Clasificación
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Circunferencia (Avg)
            </th>
            <th>
                Largo (Avg)
            </th>
            <th>
                Volumen (Sum)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nucleo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Finca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rodal)
            </td>
            <td>
                @item.Fecha.ToShortDateString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ubicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.N_Viaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoTrozasC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Clasificacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @string.Format("{0:#,0.00}", item.Circunferencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitud)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Volumen)
            </td>

            @*              <td>
            <a href="#" id="btn-trigger-modal" data-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.ViajeId">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.ViajeId">Delete</a>
        </td>*@
        </tr>
        }
    </tbody>
</table>

<div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Editar Viajes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="div_content">
                    <!--<partial name="_ViajesEdit.cshtml" />-->
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-fecini="@ViewData["FecIni"]"
           asp-route-fecfin="@ViewData["FecFin"]"
           asp-route-finca="@ViewData["FincaSelected"]"
           asp-route-rodal="@ViewData["RodalSelected"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-fecini="@ViewData["FecIni"]"
           asp-route-fecfin="@ViewData["FecFin"]"
           asp-route-finca="@ViewData["FincaSelected"]"
           asp-route-rodal="@ViewData["RodalSelected"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
        <span>Pag. @Model.PageIndex / @Model.TotalPages</span>
        <a asp-area="" asp-controller="Viajes" asp-action="Index" asp-route-id="1" asp-route-fecini="@ViewData["FecIni"]" asp-route-fecfin="@ViewData["FecFin"]" asp-route-download="true" class="btn btn-primary">Descargar</a>
    </div>
</div>

<br />
<div class="row">
    <div class="col-md-6">
        <table>
            <tbody>
                <tr>
                    <td>
                        <form asp-action="ImportFromExcel" asp-route-id="1" method="post" enctype="multipart/form-data">
                            <label class="control-label">Subir Datos de Cosecha</label>
                            <input type="file" class="" name="theExcel" />
                            <input type="submit" value="Subir Datos" />
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

EquiforestWebApp/Views/Viajes/Viaje.cshtml
@model PaginatedList<EquiforestWebApp.Models.Viajes>

@{
    ViewData["Title"] = "Viaje";
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">

    @*

    function showModal(Id) {

        $.ajax({
        url: '/Viajes/OnGetViajesEdit',
        type: 'GET',
        data: { id: Id },
        error: function (data) {
            alert("Error at getting" + data);
        },
            success: function (data) {

            $('#div_EditContent').html(data);
            $('#EditViajeModal').modal('show');
        }
    });

    $("#btnHideModal").click(function () {
        $("#EditViajeModal").modal('hide');
    });

    }

        $(document).on('click', '#btn-edit-modal', function (Id) {

            $.ajax({
                url: '/Viajes/OnGetViajesEdit',
                type: 'GET',
                data: { id: viajeId },
                success: function (data) {
                    $('#div_content').html(data);
                    $('#EditViajeModal').modal('show');
                },
                error: function () {
                    alert("Error at displaying modal");
                }
            });
    });

                  *@

    $(document).on('change', '#Rodal', function () {
        var a = $("#Rodal option:selected").val();

        $.ajax({
            url: '@Url.Action("UpdateRodalesFields", "Viajes")',
            type: "GET",
            data: { rodal: a },
            success: function (result) {

                $("#Nucleo").val(result.nucleo);
                $("#Finca").val(result.finca);
            },
            error: function (result) {

                alert("Error: " + result);


            }
        });
    });

    $(document).on('click', '#editModal', function () {

        $.ajax({

            url: '@Url.Action("EditModal", "Viajes")',
            type: "PUT",
            data: {

                id: $("#Id").val(),
                nucleo: $("#Nucleo").val(),
                finca: $("#Finca").val(),
                rodal: $("#Rodal").val(),
                fechaIngreso: $("#FechaIngreso").val(),
                ubicacion: $("#Ubicacion").val(),
                n_viaje: $("#N_Viaje").val(),
                noTrozasC: $("#NoTrozasC").val()
            },
                success: function () {
                    $("#EditViajeModal").modal('hide');
                    location.reload();

                },

        });

    });

    $(document).on('click', '#btn-createViaje-modal', function () {

        $.ajax({
            url: '/Viajes/OnGetViajesCreate',
            type: 'GET',
            success: function (data) {
                $('#div_CreateContent').html(data);
                //                $('#nucleo').text(data.nucleo);
                $('#CreateViajeModal').modal('show');
            },
            error: function () {
                alert("Error at displaying modal");
            }
        });
    });

    $(document).on('click', '#createModal', function () {
        var self = $(this);
        var actionUrl = '/Viajes/OnPostViajesCreate';
        var dataToSend = self.parents('.modal').find('form').serialize();

        $.post(actionUrl, dataToSend).done(function (data) {
            //console.log(data);
            $('#div_content').html(data);
            var newBody = $('.modal-body', data);
            var valValid = $('#div_CreateContent').find('[name="IsValid"]').val();
            var isValid = valValid == 'True';
            //newBody.find('[name="IsValid"]').val() == 'True';

            if (isValid) {
                $('#CreateViajeModal').modal('hide');
                location.reload(false);
            }

        });


        @* $.ajax({
            url: '/Viajes/EditModal/' + $('#Id').val(),
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            data: self.parents('.modal').find('form').serialize(),
            success: function (data) {
                if (data.success == true) {
                    $('#modal-person').modal('hide');
                    location.reload(false)
                } else {
                    $('#modal-person').html(data);
                }
            }
        });*@
    });

</script>

<div class="row">

    <form asp-controller="Viajes" asp-action="Viaje" method="get">
        <div class="form">

            <input type="hidden" name="pageNumber" value="1" />
            <div class="col-md-2">
                <label for="fecini">Desde</label>
                <input type="date" class="form-control" name="fecini" value="@ViewData["FecIni"]" />
            </div>
            <div class="col-md-2">
                <label for="fecfin">Hasta</label>
                <input type="date" class="form-control" name="fecfin" value="@ViewData["FecFin"]" />
            </div>
            <div class="col-md-3">
                <label for="finca">Finca</label>
                <select asp-items="ViewBag.Fincas" name="Finca" class="form-control">
                    <option selected="selected" value="@ViewBag.FincaSelected">@ViewBag.FincaSelected</option>
                </select>
            </div>
            <div class="col-md-2">
                <label for="rodal">Rodal</label>
                <select asp-items="ViewBag.Rodales" name="Rodal" class="form-control">
                    <option selected="selected" value="@ViewBag.RodalSelected">@ViewBag.RodalSelectedText</option>
                </select>
                <input type="submit" value="Filtrar" class="btn btn-default" />
            </div>
        </div>
    </form>

    @*    <div>
            <table>
                <tbody>
                    <tr>
                        <td>
                            <form asp-action="ImportFromExcel" asp-route-id="1" method="post" enctype="multipart/form-data">
                                <label class="control-label">Excel File</label>
                                <input type="file" class="" name="theExcel" />
                                <input type="submit" value="Subir Datos" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

    *@

</div>


<div>

    <div style=" display:inline-block; width: 7%;">
        <h2>Viaje</h2>
    </div>

    <p style=" display:inline-block";>
        <a href="#" id="btn-createViaje-modal" class="btn btn-info">Crear Viaje</a>
    </p>


</div>

<!--Create Viaje-->
<div>
    <div class="modal fade" id="CreateViajeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Crear Viaje</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="div_CreateContent">
                    <!--<partial name="_ViajesEdit.cshtml" />-->
                </div>
            </div>
        </div>
    </div>
</div>

<!--Edit Viaje-->
<div>
    <div class="modal fade" id="EditViajeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Editar Viajes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="div_EditContent">
                    <!--<partial name="_ViajesEdit.cshtml" />-->
                </div>
            </div>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                Nucleo
            </th>
            <th>
                Finca
            </th>
            <th>
                Rodal
            </th>
            <th>
                FechaIngreso
            </th>
            <th>
                Ubicacion
            </th>
            <th>
                No. Viaje
            </th>
            <th>
                # Trozas C
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*
                    <td>
                        @Html.DisplayFor(modelItem => item.ViajeId)
                    </td>
                *@
                <td>
                    @Html.DisplayFor(modelItem => item.Nucleo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Finca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rodal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaIngreso)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ubicacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.N_Viaje)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoTrozasC)
                </td>
                <td>
                    <a asp-controller="Trozas" asp-action="Index" asp-route-id="@item.ViajeId" class="btn btn-default">Trozas</a> |
                    @*                <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
                    <a asp-action="Delete" asp-route-id="@item.Id" asp-route-fecini="@ViewBag.FecIni" asp-route-fecfin="@ViewBag.FecFin" asp-route-rodal="@ViewBag.RodalSelected" asp-route-finca="@ViewBag.FincaSelected">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<div class="row">
    <div class="col-md-12">
        <a asp-action="Viaje"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-fecini="@ViewData["FecIni"]"
           asp-route-fecfin="@ViewData["FecFin"]"
           asp-route-finca="@ViewData["FincaSelected"]"
           asp-route-rodal="@ViewData["RodalSelected"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="Viaje"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-fecini="@ViewData["FecIni"]"
           asp-route-fecfin="@ViewData["FecFin"]"
           asp-route-finca="@ViewData["FincaSelected"]"
           asp-route-rodal="@ViewData["RodalSelected"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
        <span>Pag. @Model.PageIndex / @Model.TotalPages</span>
    </div>
</div>